language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.2"

install:
  - npm install -g babel-cli
  - npm install

script:
  - npm --version
  - npm run prepublish

deploy:
    provider: npm
    email: adrie.k@gmail.com
    api_key: NPM_REGISTRY_AUTH_TOKEN
