language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '7'
  - '6'
  - '4'

before_script:
  - npm prune

install:
  - npm install -g babel-cli
  - npm install

script:
  - npm --version
  - npm run prepublish

after_success:
  - npm run semantic-release
